try publishing junit report from erlang workflow

diff --git a/.github/workflows/erlang.yml b/.github/workflows/erlang.yml
--- a/.github/workflows/erlang.yml
+++ b/.github/workflows/erlang.yml
@@ -45,13 +45,11 @@ jobs:
     - name: Common Test tests
       run: rebar3 ct --cover
 
-    - name: Upload Test Report
-      uses: actions/upload-artifact@v3
-      if: always() # always run even if the previous step fails
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: junit-test-results
-        path: '**/_build/test/logs/*/junit_report.xml'
-        retention-days: 1
+        report_paths: '**/_build/test/logs/*/junit_report.xml'
 
     - name: XRef
       run: rebar3 xref
